version: '3'

dotenv: ['.env']

interval: 500ms

tasks:

  build:
    cmds:
      - go build -tags dev -o bin/tui cmd/main.go
    generates:
      - './bin/tui'
    sources:
      - 'cmd/**/*.go'
      - 'pkg/**/*.go'

  prod:
    cmds:
      - go build -tags prod -o bin/tui cmd/main.go
    generates:
      - './bin/tui'
    sources:
      - 'cmd/**/*.go'
      - 'pkg/**/*.go'

  tui:
    env:
      DEBUG: 1
    cmds:
      - task: build
      - bin/tui

  tui_log:
    cmds:
      - rm -f debug.log
      - touch debug.log
      - tail -f debug.log

  fmt:
    cmds:
      - go fmt ./...
    sources:
      - '**/*.go'
