version: '3'

dotenv: ['.env']

interval: 500ms

tasks:

  build:
    cmds:
      - go build -tags dev -o bin/qt cmd/main.go
    generates:
      - './bin/qt'
    sources:
      - 'cmd/**/*.go'
      - 'pkg/**/*.go'

  prod:
    vars:
      GOOS: '{{default "darwin" .GOOS}}'
      GOARCH: '{{default "arm64" .GOARCH}}'
    cmds:
      - echo "Building for {{.GOOS}}/{{.GOARCH}}"
      - GOOS={{.GOOS}} GOARCH={{.GOARCH}} go build -tags prod -o bin/qt-{{.GOOS}}-{{.GOARCH}} cmd/main.go
    generates:
      - './bin/qt-{{.GOOS}}-{{.GOARCH}}'
    sources:
      - 'cmd/**/*.go'
      - 'pkg/**/*.go'

  prod_mac:
    cmds:
      - task: prod
        vars:
          GOOS: 'darwin'
          GOARCH: 'arm64'

  prod_linux:
    cmds:
      - task: prod
        vars:
          GOOS: 'linux'
          GOARCH: 'amd64'

  tui:
    cmds:
      - task: build
      - bin/qt -d -c ~/.soq-dev

  kill:
    cmds:
      - kill -9 $(ps -xf | grep 'task tui' | awk 'NR==1{ print $2 }')

  install:
    cmds:
      - task: prod
      - cp bin/qt /usr/local/bin/qt

  log:
    cmds:
      - rm -f debug.log
      - touch debug.log
      - tail -f debug.log

  fmt:
    cmds:
      - go fmt ./...
    sources:
      - '**/*.go'
