version: '3'

dotenv: ['.env']

interval: 500ms

tasks:

  build:
    cmds:
      - go build -tags dev -o bin/qt cmd/main.go
    generates:
      - './bin/qt'
    sources:
      - 'cmd/**/*.go'
      - 'pkg/**/*.go'

  prod:
    cmds:
      - go build -tags prod -o bin/qt cmd/main.go
    generates:
      - './bin/qt'
    sources:
      - 'cmd/**/*.go'
      - 'pkg/**/*.go'

  tui:
    env:
      DEBUG: 1
    cmds:
      - task: build
      - bin/qt

  install:
    cmds:
      - task: prod
      - cp bin/qt /usr/local/bin/qt

  log:
    cmds:
      - rm -f debug.log
      - touch debug.log
      - tail -f debug.log

  fmt:
    cmds:
      - go fmt ./...
    sources:
      - '**/*.go'
