name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GOPRIVATE: "github.com/mole-squad/*"

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Setup go-task
      uses: pnorton5432/setup-task@v1

    - uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SOQ_API_DEPLOY_KEY }}

    - name: Configure for private packages
      run: |
        git config --global url.git@github.com:.insteadOf https://github.com/

    - name: Build
      run: task build

